<prg>          ::= <expr> | <expr>\n<expr>

<expr>         ::= <arthexpr> | <ifexpr>
<arthexpr>     ::= (<operand> <operand> <op>)
<ifexpr>       ::= IF <operand> <operand> <operand> <operand>
<operand>      ::= <signumber> | <expr>
<op>           ::= + | x | / | -

<signumber>    ::= <nonzerodigit> | <nonzerodigit><number>
<number>       ::= <digit> | <digit><number>
<nonzerodigit> ::= 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<digit>        ::= 0 | <nonzerodigit>
