<prg>          ::= <expr> | <expr><EOL><expr>

<expr>         ::= <arthexpr> | <ifexpr>
<arthexpr>     ::= (<signumber> <signumber> <op>)
<op>           ::= + | x | / | -
<ifexpr>       ::= IF <expr> <expr> <expr> <expr>

<signumber>    ::= <nonzerodigit> | <nonzerodigit><number>
<number>       ::= <digit> | <digit><number>
<nonzerodigit> ::= 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<digit>        ::= 0 | <nonzerodigit>
